In [2]:
import torch

In [4]:
x = torch.empty(4,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [5]:
x = torch.rand(4,2)
print(x)

tensor([[0.6362, 0.1750],
        [0.1555, 0.8264],
        [0.1891, 0.4862],
        [0.0190, 0.8647]])


In [7]:
x = torch.zeros(4,2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [8]:
x = torch.tensor([5.5, 3])  # create tensor from data
print(x)                # tensor([5.5000, 3.0000])

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)                # tensor([[

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                # tensor([[-0.3366,  0.1288, -0.6434],

tensor([[-1.4328, -0.9068,  0.5648],
        [-0.7691,  0.5159,  0.5336],
        [-0.7007, -0.7531,  0.9615],
        [ 1.1107, -1.2833,  0.6290],
        [-1.2410, -0.9598,  0.5540]])
